language: go
go:
  1.11.x
sudo: false
env:
  - NODE_VERSION="10.15" PORT=8080

before_install:
  - nvm install $NODE_VERSION
install:
  - npm ci
  - go get ./...
  - go build
script:
  - go test ./... -v
  - npm test
cache:
  npm: true # this cashes ~/.npm folder on Travis
  directories:
  # we also need to cache folder with Cypress binary
    - ~/.cache
